CREATE TABLE LU_CITIES
(
 CITY_ID   number NOT NULL,
 CITY_DESC varchar2(40 byte) NULL,
 LATITUDE  number(10,7) NULL,
 LONGITUDE number(10,7) NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( CITY_ID )
);

CREATE TABLE LU_COMPANIES
(
 COMPANY_ID   number NOT NULL,
 COMPANY_DESC varchar2 (40 byte) NOT NULL,
 CONSTRAINT PK_6 PRIMARY KEY ( COMPANY_ID )
);

CREATE TABLE LU_FARES
(
 FARE_ID   number NOT NULL,
 FARE_DESC varchar2 (30 byte) NOT NULL,
 CONSTRAINT PK_21 PRIMARY KEY ( FARE_ID )
);

CREATE TABLE LU_TRAVEL_TYPES
(
 TRAVEL_TYPE_ID   number NOT NULL,
 TRAVEL_TYPE_DESC varchar2(30) NOT NULL,
 CONSTRAINT PK_25 PRIMARY KEY ( TRAVEL_TYPE_ID )
);

CREATE TABLE LU_VEHICLE_CLASSES
(
 CLASS_ID   number NOT NULL,
 CLASS_DESC varchar2 (30 byte) NOT NULL,
 CONSTRAINT PK_29 PRIMARY KEY ( CLASS_ID )
);

CREATE TABLE DIM_TICKET_PRICES(
    COMPANY_ID number,
    ORIGIN_ID number,
    DESTINATION_ID number,
    DEPARTURE timestamp,
    ARRIVAL timestamp,
    TRAVEL_DURATION number(5,2),
    TRAVEL_TYPE_ID number,
    CLASS_ID number,
	FARE_ID number,
	SEATS number,
    PRICE number(6,2)
);